
import type { User, Post } from './types';

export const users: User[] = [
  { id: 1, name: 'Jeffrey Epstein', avatarUrl: 'https://jeffedin.vercel.app/images/epstein.jpg' },
  { id: 2, name: 'Ghislaine Maxwell', avatarUrl: 'https://jeffedin.vercel.app/images/maxwell.jpg' },
  { id: 3, name: 'Prince Andrew', avatarUrl: 'https://jeffedin.vercel.app/images/prince-andrew.jpg' },
  { id: 4, name: 'Bill Clinton', avatarUrl: 'https://jeffedin.vercel.app/images/clinton.jpg' },
  { id: 5, name: 'Donald Trump', avatarUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbHwi_ak3Kr89qrYmWxrcmDb364vevyXHx9w&s' },
  { id: 6, name: 'Stephen Hawking', avatarUrl: 'https://ichef.bbci.co.uk/ace/standard/976/cpsprodpb/985A/production/_101220093_046642501-1.jpg' },
  { id: 7, name: 'Lawrence Summers', avatarUrl: 'https://jeffedin.vercel.app/images/summers.jpg' },
  { id: 8, name: 'Bill Gates', avatarUrl: 'https://jeffedin.vercel.app/images/gates.jpg' },
  { id: 9, name: 'Kevin Spacey', avatarUrl: 'https://epstagram.xyz/images/pfp/kevin-spacey.png' },
  { id: 10, name: 'Chris Tucker', avatarUrl: 'https://epstagram.xyz/images/pfp/chris-tucker.png' },
  { id: 11, name: 'Naomi Campbell', avatarUrl: 'https://epstagram.xyz/images/pfp/naomi-campbell.png' },
  { id: 12, name: 'Mark Zuckerberg', avatarUrl: 'https://i.imgur.com/n742t1i.jpeg'},
];

export const posts: Post[] = [
  {
    id: 1,
    userId: 1,
    timestamp: '15 hours ago',
    text: 'Another successful week of networking and fostering global connections. The island provides such a wonderful, private venue for important discussions.',
    imageUrl: 'https://i.imgur.com/sFE8P2d.jpeg',
    likes: 431,
    comments: 88,
    isLiked: false,
    commentList: [],
  },
  {
    id: 2,
    userId: 4,
    timestamp: '1 day ago',
    text: 'Enjoyed a fascinating trip with Jeffrey. We discussed the future of global philanthropy and youth outreach. Always inspiring to connect with sharp minds. The flight back was smooth!',
    imageUrl: 'https://i.imgur.com/qSHxftz.jpeg',
    likes: 1998,
    comments: 789,
    isLiked: false,
    commentList: [],
  },
  {
    id: 3,
    userId: 2,
    timestamp: '2 days ago',
    text: 'Making sure all our guests are comfortable is my top priority. A personal touch goes a long way. So glad everyone enjoyed the party last night!',
    likes: 350,
    comments: 45,
    isLiked: false,
    commentList: [],
  },
  {
    id: 4,
    userId: 8,
    timestamp: '2 days ago',
    text: 'The code for the future is complex. Flew down to brainstorm with some fellow visionaries. The key to solving the world\'s problems is unconventional thinking.',
    imageUrl: 'https://epstagram.xyz/images/posts/bill-gates-and-epstein.png',
    likes: 1500,
    comments: 215,
    isLiked: false,
    commentList: [],
  },
    {
    id: 11,
    userId: 8,
    timestamp: '2 days ago',
    text: 'Productive meeting with Jeffrey and some other great minds. Discussing how to scale up our philanthropic impact. The location was very... secure.',
    imageUrl: 'https://i.dailymail.co.uk/1s/2026/02/02/18/105973447-15513681-Epstein_has_a_meeting_with_Gates_and_another_man_at_an_undisclos-a-7_1770057514279.jpg',
    likes: 1850,
    comments: 310,
    isLiked: false,
    commentList: [],
  },
  {
    id: 5,
    userId: 3,
    timestamp: '3 days ago',
    text: 'A delightful getaway. One must concede, the hospitality was truly fit for a royal. I have absolutely no memory of anything specific, but I\'m sure it was all perfectly pleasant.',
    imageUrl: 'https://i.imgur.com/GzBBL6j.jpeg',
    likes: 310,
    comments: 77,
    isLiked: false,
    commentList: [],
  },
  {
    id: 6,
    userId: 7,
    timestamp: '4 days ago',
    text: 'Economics is about managing scarce resources. Time is the most scarce of all. Glad to have spent some of it discussing fiscal policies and other... assets... with Jeff.',
    likes: 210,
    comments: 33,
    isLiked: false,
    commentList: [],
  },
  {
    id: 7,
    userId: 6,
    timestamp: '5 days ago',
    text: 'The theoretical applications of string theory on a sub-atomic level are fascinating. The barbecue was also quite good.',
    imageUrl: 'https://epstagram.xyz/images/posts/stephen-hawking-on-epstein-island.png',
    likes: 890,
    comments: 210,
    isLiked: false,
    commentList: [],
  },
  {
    id: 8,
    userId: 5,
    timestamp: '6 days ago',
    text: 'Jeff was a terrific guy. He liked beautiful women, and I like beautiful women. I\'m not gonna say he was a bad guy. Great parties. The best parties.',
    imageUrl: 'https://epstagram.xyz/images/posts/donald-trump-epstein-and-ghislaine.png',
    likes: 1024,
    comments: 420,
    isLiked: false,
    commentList: [],
  },
  {
    id: 9,
    userId: 1,
    timestamp: '1 week ago',
    text: 'Just had the temple repainted. The new gold leaf really brings out the mysterious, esoteric vibe we were going for. Perfect for quiet contemplation.',
    imageUrl: 'https://i.dailymail.co.uk/1s/2026/02/02/18/105979081-15513681-A_diagram_mapping_Epstein_s_inner_circle_released_by_the_Justice-a-12_1770057514516.jpg',
    likes: 666,
    comments: 150,
    isLiked: false,
    commentList: [],
  },
  {
    id: 10,
    userId: 9,
    timestamp: '1 week ago',
    text: 'On my way to a private acting workshop on a secluded island. The best way to really get into character. No distractions.',
    imageUrl: 'https://epstagram.xyz/images/posts/kevin-spacey-on-the-lolita-express.png',
    likes: 451,
    comments: 112,
    isLiked: false,
    commentList: [],
  },
];
